# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               uykusuz adam
tagline:             'uykusuz adam blog'
description:         '.Net framework, asp.net mvc, javascript and some back-end stuffs from Abdurrahman Işık'
url:                 http://abdurrahman.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Abdurrahman Işık
  url:               https://twitter.com/xJason21
  email:             isikabdurrahman@yandex.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
