locale: "en-US"
title: Abdurrahman Işık
url: "abdurrahman.github.io"
baseurl: "/"
google_analytics_key: "UA-52566441-1"

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Abdurrahman Işık
  email: isikabdurrahman@yandex.com
  twitter: xJason21

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: 4VavwEhPcFW-Zg5-ky5XTinfrYrEKHwodn9UonI7kOA
  bing: # 1234
  alexa: D442E90CE6C74A3C4B18DCDEB827EAB4
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
